### ISSUE TITLE
[Wiki Error]: Wiki CT Page links to Spoiled wiki

### ISSUE THREAD

**Issue by brisingraerowing** [Mrbysco/AngryMobs#1]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

N/A

### Mod version

N/A

### Java version

N/A

### Issue Description

The two version links on the CraftTweaker wiki page here link to the Spoiled wiki instead.

**Comment by Mrbysco** [comment]
Fixed
