### ISSUE TITLE
[Bug]: json file has no effect on the game?

### ISSUE THREAD

**Issue by Drakkxs** [Mrbysco/AngryMobs#2]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.0

### Minecraft version

1.20.1

### Mod version

4.1.0

### Java version

Not sure?

### Issue Description

Using this config file for the json I was hoping to see sheep do little to none while cows do more including other enhancements but no version of "minecraft:generic.attack_damage" or "generic.attack_damage" has seemed to work.

```
{
  "additionList": [
    {
      "entity": "minecraft:allay",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:axolotl",
      "attribute": "generic.attack_damage",
      "value": 2.0  
    },
    {
      "entity": "minecraft:bat",
      "attribute": "generic.attack_damage",
      "value": 0.5  
    },
    {
      "entity": "minecraft:bee",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:chicken",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:cod",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:cow",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:dolphin",
      "attribute": "generic.attack_damage",
      "value": 2.0  
    },
    {
      "entity": "minecraft:donkey",
      "attribute": "generic.attack_damage",
      "value": 2.0  
    },
    {
      "entity": "minecraft:fox",
      "attribute": "generic.attack_damage",
      "value": 2.0  
    },
    {
      "entity": "minecraft:glow_squid",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:goat",
      "attribute": "generic.attack_damage",
      "value": 4.0  
    },
    {
      "entity": "minecraft:horse",
      "attribute": "generic.attack_damage",
      "value": 3.0  
    },
    {
      "entity": "minecraft:llama",
      "attribute": "generic.attack_damage",
      "value": 3.0  
    },
    {
      "entity": "minecraft:mooshroom_cow",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:mule",
      "attribute": "generic.attack_damage",
      "value": 3.0  
    },
    {
      "entity": "minecraft:ocelot",
      "attribute": "generic.attack_damage",
      "value": 3.0  
    },
    {
      "entity": "minecraft:panda",
      "attribute": "generic.attack_damage",
      "value": 4.0  
    },
    {
      "entity": "minecraft:parrot",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:pig",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:rabbit",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:salmon",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:sheep",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:squid",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:strider",
      "attribute": "generic.attack_damage",
      "value": 4.0  
    },
    {
      "entity": "minecraft:turtle",
      "attribute": "generic.attack_damage",
      "value": 1.0  
    },
    {
      "entity": "minecraft:villager",
      "attribute": "generic.attack_damage",
      "value": 0.0  
    },
    {
      "entity": "minecraft:wolf",
      "attribute": "generic.attack_damage",
      "value": 4.0  
    }
  ]
}

```

While not editing the damage, affected entities that do attack back also have no damage attribute?

![image](https://github.com/Mrbysco/AngryMobs/assets/70417194/5a4439fa-463e-4f66-9733-b8c64c4dc1b9)

### Additional Information

Here is the in-game configuration.

#Common settings
[Common]
	#When true makes all vanilla animals attack you if you hurt them
	angryAnimals = true
	#When true makes all vanilla animals call for reinforcement when you hurt them
	angryReinforcements = true
	#When true makes all vanilla animals attack you on sight
	aggressiveAnimals = false
	#When true makes the melee goals add the mobs attack damage and knockback onto the specified values
	useAttributes = true

**Comment by Mrbysco** [comment]
Can you provide the log file?

**Comment by Drakkxs** [comment]
[latest.log](https://github.com/Mrbysco/AngryMobs/files/14813109/latest.log)

**Comment by Drakkxs** [comment]
Does that work?

**Comment by Mrbysco** [comment]
Did you edit the json after the game had already been loaded? If you did you need to restart the game as the json only gets loaded once when Entity attributes are being initialized. If you edited the json after game load was complete then it won't load the configured attributes until you restart.

If an attribute gets added to an entity then it'll output it in the log which I don't see happening in yours making me believe you edited it after game load

**Comment by Drakkxs** [comment]
Do have you have an example of the mod functioning? Or a demonstration of the mod in action that shows that it works? Because I have tried multiple times in different ways to get the mod to work. I have some experience with messing with config files. Can I please see it in action through a video? Maybe I'm doing something wrong and it'll probably show if you do it?

**Comment by Drakkxs** [comment]
Or I could try making a video of me starting up the mod?

**Comment by Mrbysco** [comment]
I'm able to use your json setup in Forge 1.20.1 47.1.3 which is what the mod is built against.
![image](https://github.com/Mrbysco/AngryMobs/assets/9308260/b199615c-48cf-44b0-af44-3ca527f46756)

**Comment by Mrbysco** [comment]
Even tried 47.2.0 which also worked fine

**Comment by Drakkxs** [comment]
Well, thank you for your help then. It's likely some conflict I'm not aware of.
