### ISSUE TITLE
[Bug]: it doesn't work

### ISSUE THREAD

**Issue by the-punt** [Mrbysco/AngryMobs#4]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.3.0

### Minecraft version

1.20.1

### Mod version

4.1.1

### Java version

I don't know what this means

### Issue Description

i cannot configure the file (angrymobs-common) and when i put "true" on everything and start up the game, the mobs do not attack me or anything else. currently everything is set to true, 

i also cannot tweak anything with crafttweaker.

interestingly, if i use a configuration mod that allows configuring, the mobs do attack me, but when i go to the page it says it's configuring and change it myself via notepad, it doesn't work.

i could use a configuring mod, but i'm more interested in using the extra things you can do with crafttweaker, which this configuring mod does NOT allow.

below is the image of the notepad, i've set everything to true, but mobs do NOT attack me.
![image](https://github.com/user-attachments/assets/4c19b2ef-7083-4fc9-b1ec-ef19f1829ca0)

**Comment by Mrbysco** [comment]
There are some text programs that save configs in a way in which the config system Forge uses struggles and causes the config to be reset. (Notepad++ is notorious for that)

**Comment by Mrbysco** [comment]
The AI goals do not get added retroactively. So if you have created a world and changed the config after creation. Any existing mobs won't have the changes applied, only newly spawned mobs will have the changes get applied

**Comment by the-punt** [comment]
> There are some text programs that save configs in a way in which the config system Forge uses struggles and causes the config to be reset. (Notepad++ is notorious for that)

alright, so notepad++ and notepad do not work for me, i also tried visual studio code which didn't work either, what programs do you recommend?

**Comment by Mrbysco** [comment]
I've never had issues with Sublime Text myself, but I rarely hand-edit the config. It shouldn't matter for the crafttweaker scripts though, only configs can break like that

**Comment by the-punt** [comment]
![image](https://github.com/user-attachments/assets/a877ecec-307b-4b5c-b254-9759df851aae)
![image](https://github.com/user-attachments/assets/8eaba7a7-09db-47ef-aabf-ad300a26c4d4)
it didn't work, i inserted it onto both of these files in sublime text, what else could i do?

**Comment by Mrbysco** [comment]
You can't merge the 2 files. The config is separate from the attribute json for a reason
